### ISSUE TITLE
feature: Is there any way to apply atomic-chrome-url-major-mode-alist to some url by force ?

### ISSUE THREAD

**Issue by liuyinz** [KarimAziev/atomic-chrome#3]
according to function
```elisp
(defun atomic-chrome-set-major-mode (url)
  "Set major mode for editing buffer depending on URL.
`atomic-chrome-url-major-mode-alist' can be used to select major mode.
The specified major mode is used if URL matches to one of the alist,
otherwise fallback to `atomic-chrome-default-major-mode'"
  (let ((mode (assoc-default url atomic-chrome-url-major-mode-alist
                             'string-match)))
    (cond ((and buffer-file-name
                (file-name-extension buffer-file-name))
           (set-auto-mode))
          (mode (funcall mode))
          (t (funcall atomic-chrome-default-major-mode)))))
```
The major mode of a buffer is primarily determined by the extension sent back by the website (if present). However, some websites may return inaccurate values, or users may want to enforce the use of the custom variable `atomic-chrome-url-major-mode-alist` for matching. Could you provide an option to adjust the priority of some website so that the custom regex is always used first?

 For example, the URL https://react.docschina.org/reference/react/useContext returns `js` as the extension and set to `js-ts-mode` but I want to enforce using `js-jsx-mode`  always in this website.

**Comment by KarimAziev** [comment]
Hi, I think you can achieve this by combining `atomic-chrome-create-file-strategy` with hooks in `atomic-chrome-edit-mode-hook`.

1. This step is optional. If you want your file for `react.docschina.org` to be created in a specific directory:

```elisp
(add-to-list 'atomic-chrome-create-file-strategy
             '("~/my-react-scratch-dir" ;; The edit file should be created in this directory.
               :url ;; If the hostname of the URL is one of:
               ("react.docschina.org")
               ;; AND the file extension is one of:
               :extension
               ("js")))
```

2. Add a custom hook that will check the directory. If you didn't add the rule, omit the file check in the provided example:
```elisp
(defun my-setup-edit-buffer ()
  (when (and buffer-file-name
             (file-in-directory-p buffer-file-name "~/my-react-scratch-dir")
             (equal (file-name-extension buffer-file-name) "js")
             (not (eq major-mode 'js-jsx-mode))) ; This line is important to prevent recursion.
    (js-jsx-mode)))
(add-hook 'atomic-chrome-edit-mode-hook 'my-setup-edit-buffer)
```

**Comment by liuyinz** [comment]
Thanks for your solution !

**Comment by liuyinz** [comment]
@KarimAziev Actually I would prefer to use buffer's origin url to match regexp rather than directory to operate in the hooks,
is there any method to get origin info like url from the edited buffer ? The approach of creating a new directory to solve the problem is really too cumbersome and unnecessary.

**Comment by KarimAziev** [comment]
@liuyinz 
Okay, I will add some settings to enforce the precedence of URL regexes.

**Comment by liuyinz** [comment]
Oh yes, that is a nice workaround. However, I use lsp-bridge to provide completions, which is only available for files.... For now, I write a advice to overwrite the determined function which related to major mode  priority, it's ugly but effective. I agree with that website returned value if present  should has top priority, so it's just a temporary solution. Buffer local value containing url info or methods is a better fix.

**Comment by liuyinz** [comment]
> @liuyinz 
> Okay, I will add some settings to enforce the precedence of URL regexes.

A website may use different file extensions for different input areas, so the current priority arrangements is more reasonable. Although I patch a override advice to improve regexp priority, I still think adjust priority could not solve all problem. For example, if a website may  return one of js,css,python three kinds of modes and user only want to override css major mode, one must use hook to filter and applied new rule.

**Comment by KarimAziev** [comment]
So, if I understand you correctly, you are suggesting adding a new local variable with the URL? That indeed makes sense, I will add it soon, probably tomorrow.

**Comment by liuyinz** [comment]
Maybe do not need to create a local var, just put `url, title, extension` these info into hashtable
 when create the buffer is enough, so that I can extract these info in the edit hook. how do you think ?
```elisp
(defun atomic-chrome-create-buffer (socket url title text &optional extension
                                           line column rect)
  (unless extension (setq extension
                          (condition-case nil
                              (progn
                                (require 'url-parse)
                                (when-let ((ext (file-name-extension
                                                 (car (url-path-and-query
                                                       (url-generic-parse-url
                                                        url))))))
                                  (unless (> (length ext) 5)
                                    ext)))
                            (error nil))))
  (let* ((suffix (atomic-chrome-normalize-file-extension extension))
         (file (atomic-chrome-make-file title suffix url))
         (buffer (if file
                     (find-file-noselect file)
                   (generate-new-buffer (atomic-chrome--safe-substring
                                         (if (string-empty-p title) "No title"
                                           title)
                                         atomic-chrome-max-filename-size)))))
    (with-current-buffer buffer
      (puthash buffer
;;; Add infos into hash-table when create buffer, maybe plist is more clear
;;; (:socket socket :url url :extension extension :method (atomic-chrome-show....)
               (list socket url title extension 
(atomic-chrome-show-edit-buffer
                             buffer title
                             rect))
               atomic-chrome-buffer-table)
      (let ((buffer-undo-list t))
        (insert text))
      (atomic-chrome-set-major-mode url)
      (atomic-chrome--goto-position line column))))
```

**Comment by KarimAziev** [comment]
Yes, I think it's a good approach. I will do more testing, and then I am going to merge your pull request. Thanks.
